// Generated by Break Your Assumptions v0.1.0 (MIT)
// Lab: The perfect backup - assumption: A successful backup file means the app can be recovered.
// Run: node --test backup.test.cjs
//
// WHAT THIS FILE TESTS
// As downloaded, this file verifies the reference implementation bundled below.
// It does NOT test your application until you connect an adapter: replace the body
// of underTest() with a call into YOUR code that returns {pass, actual, expected}
// derived from observed application state. See docs/ADAPTING_TESTS.md.

const test = require('node:test');
const assert = require('node:assert/strict');

// ---- Reference simulation (teaching model, self-contained) ----
function backup(fixed, includeAttachment = false) {
  if (typeof includeAttachment !== 'boolean') throw new TypeError('includeAttachment must be a boolean');
  const live = { users: [{ id: 1, name: 'Mira' }], documents: [{ id: 7, owner: 1, attachment: 'file_7' }],
    attachments: { file_7: 'example attachment bytes' } };
  const archive = fixed ? JSON.stringify(live) : JSON.stringify({ users: live.users,
    documents: live.documents, attachments: includeAttachment ? live.attachments : {} });
  const restored = JSON.parse(archive);
  // Probe the reconstructed application, not merely the backup file's existence.
  const checks = [restored.users.some(u => u.id === 1), restored.documents.some(d => d.id === 7),
    restored.documents.every(d => restored.attachments[d.attachment] === live.attachments[d.attachment])];
  const actual = checks.filter(Boolean).length;
  return { pass: actual === 3, actual, expected: 3, unit: 'restore checks passed',
    trace: [`Archive exists: ${archive.length} characters.`, `User lookup: ${checks[0] ? 'PASS' : 'FAIL'}.`,
      `Document lookup: ${checks[1] ? 'PASS' : 'FAIL'}.`, `Open attachment: ${checks[2] ? 'PASS' : 'FAIL'}.`] };
}

// ---- ADAPTER: replace this body to test your own application ----
// Currently it calls the bundled repaired reference, so the tests below check the reference.
function underTest(condition) {
  return backup(true, condition);
}

const invariant = "The restored user, document, and attachment all remain accessible.";
const conditions = [
  {"value":false,"label":"Database only","originalBreaks":true},
  {"value":true,"label":"Database + attachment (control)","originalBreaks":false}
];

// Invariant checks: these run against underTest(), i.e. your adapter once connected.
for (const condition of conditions) {
  test(`${invariant} [${condition.label}]`, () => {
    const result = underTest(condition.value);
    assert.equal(result.pass, true);
    assert.deepEqual(result.actual, result.expected);
  });
}

// Negative controls: these always call the bundled ORIGINAL reference, never your adapter.
// They prove the invariant can fail, and that the no-failure controls pass.
for (const condition of conditions) {
  test(`Reference original ${condition.originalBreaks ? 'violates' : 'satisfies'} the invariant [${condition.label}]`, () => {
    assert.equal(backup(false, condition.value).pass, !condition.originalBreaks);
  });
}
