// Generated by Break Your Assumptions v0.1.0 (MIT)
// Lab: The lying clock - assumption: Later events always have larger timestamps.
// Run: node --test clock.test.cjs
//
// WHAT THIS FILE TESTS
// As downloaded, this file verifies the reference implementation bundled below.
// It does NOT test your application until you connect an adapter: replace the body
// of underTest() with a call into YOUR code that returns {pass, actual, expected}
// derived from observed application state. See docs/ADAPTING_TESTS.md.

const test = require('node:test');
const assert = require('node:assert/strict');

// ---- Reference simulation (teaching model, self-contained) ----
function clock(fixed, rollback = 500) {
  if (!Number.isInteger(rollback) || rollback < 0 || rollback > 3600000) throw new RangeError('rollback must be an integer from 0 to 3600000 ms');
  const first = 10000, second = first + 100 - rollback;
  const events = [{ id: 'A', wall: first, sequence: 1 }, { id: 'B', wall: second, sequence: 2 }];
  const ordered = [...events].sort((a, b) => fixed ? a.sequence - b.sequence : a.wall - b.wall);
  const actual = ordered.map(e => e.id).join(' → ');
  return { pass: actual === 'A → B', actual, expected: 'A → B', unit: 'event order',
    trace: [`A happens first: wall clock ${first} ms, sequence 1.`,
      `Clock correction: −${rollback} ms. B happens 100 ms later: wall clock ${second} ms, sequence 2.`,
      `Sorted by ${fixed ? 'local sequence' : 'wall-clock timestamp'}: ${actual}.`] };
}

// ---- ADAPTER: replace this body to test your own application ----
// Currently it calls the bundled repaired reference, so the tests below check the reference.
function underTest(condition) {
  return clock(true, condition);
}

const invariant = "The known producer order stays A then B regardless of the simulated wall-clock correction.";
const conditions = [
  {"value":500,"label":"Back 500 ms","originalBreaks":true},
  {"value":5000,"label":"Back 5 seconds","originalBreaks":true},
  {"value":0,"label":"No correction (control)","originalBreaks":false}
];

// Invariant checks: these run against underTest(), i.e. your adapter once connected.
for (const condition of conditions) {
  test(`${invariant} [${condition.label}]`, () => {
    const result = underTest(condition.value);
    assert.equal(result.pass, true);
    assert.deepEqual(result.actual, result.expected);
  });
}

// Negative controls: these always call the bundled ORIGINAL reference, never your adapter.
// They prove the invariant can fail, and that the no-failure controls pass.
for (const condition of conditions) {
  test(`Reference original ${condition.originalBreaks ? 'violates' : 'satisfies'} the invariant [${condition.label}]`, () => {
    assert.equal(clock(false, condition.value).pass, !condition.originalBreaks);
  });
}
