// Generated by Break Your Assumptions v0.1.0 (MIT)
// Lab: Offline twins - assumption: The latest uploaded document contains the latest edits.
// Run: node --test offline.test.cjs
//
// WHAT THIS FILE TESTS
// As downloaded, this file verifies the reference implementation bundled below.
// It does NOT test your application until you connect an adapter: replace the body
// of underTest() with a call into YOUR code that returns {pass, actual, expected}
// derived from observed application state. See docs/ADAPTING_TESTS.md.

const test = require('node:test');
const assert = require('node:assert/strict');

// ---- Reference simulation (teaching model, self-contained) ----
function offline(fixed, sameField = false) {
  if (typeof sameField !== 'boolean') throw new TypeError('sameField must be a boolean');
  const base = { title: 'Draft', body: 'Hello' };
  const patchA = { title: 'Final' }, patchB = sameField ? { title: 'Review' } : { body: 'Hello world' };
  const snapshotA = { ...base, ...patchA }, snapshotB = { ...base, ...patchB };
  const trace = ['Both devices start with title=Draft, body=Hello.', 'Device A edits title to Final.',
    sameField ? 'Device B edits title to Review.' : 'Device B edits body to Hello world.'];
  let result, conflicts = {};
  if (!fixed) { result = snapshotB; trace.push('A uploads, then B replaces the entire document. A’s edit is lost.'); }
  else {
    result = { ...snapshotA };
    for (const [key, value] of Object.entries(patchB)) {
      if (Object.hasOwn(patchA, key) && patchA[key] !== value) {
        conflicts[key] = [patchA[key], value];
        trace.push(`Conflict on ${key}: retain both values for a human decision.`);
      } else { result[key] = value; trace.push(`Merge B’s changed field: ${key}.`); }
    }
  }
  const preserved = sameField ? (conflicts.title?.length === 2 ? 2 : 1)
    : Number(result.title === 'Final') + Number(result.body === 'Hello world');
  return { pass: preserved === 2, actual: preserved, expected: 2, unit: 'edits retained', trace, result, conflicts };
}

// ---- ADAPTER: replace this body to test your own application ----
// Currently it calls the bundled repaired reference, so the tests below check the reference.
function underTest(condition) {
  return offline(true, condition);
}

const invariant = "Both edits remain recoverable, either merged or explicitly retained as a conflict.";
const conditions = [
  {"value":false,"label":"Different fields","originalBreaks":true},
  {"value":true,"label":"Same field (conflict)","originalBreaks":true}
];

// Invariant checks: these run against underTest(), i.e. your adapter once connected.
for (const condition of conditions) {
  test(`${invariant} [${condition.label}]`, () => {
    const result = underTest(condition.value);
    assert.equal(result.pass, true);
    assert.deepEqual(result.actual, result.expected);
  });
}

// Negative controls: these always call the bundled ORIGINAL reference, never your adapter.
// They prove the invariant can fail, and that the no-failure controls pass.
for (const condition of conditions) {
  test(`Reference original ${condition.originalBreaks ? 'violates' : 'satisfies'} the invariant [${condition.label}]`, () => {
    assert.equal(offline(false, condition.value).pass, !condition.originalBreaks);
  });
}
