// Generated by Break Your Assumptions v0.1.0 (MIT)
// Lab: Payment déjà vu - assumption: One payment event means one delivery.
// Run: node --test payment.test.cjs
//
// WHAT THIS FILE TESTS
// As downloaded, this file verifies the reference implementation bundled below.
// It does NOT test your application until you connect an adapter: replace the body
// of underTest() with a call into YOUR code that returns {pass, actual, expected}
// derived from observed application state. See docs/ADAPTING_TESTS.md.

const test = require('node:test');
const assert = require('node:assert/strict');

// ---- Reference simulation (teaching model, self-contained) ----
function payment(fixed, deliveries = 3) {
  if (!Number.isInteger(deliveries) || deliveries < 1 || deliveries > 1000) throw new RangeError('deliveries must be an integer from 1 to 1000');
  let balance = 0;
  const seen = new Set(), trace = [];
  for (let n = 1; n <= deliveries; n++) {
    const event = { id: 'evt_42', amount: 100 };
    if (fixed && seen.has(event.id)) { trace.push(`Delivery ${n}: duplicate ignored.`); continue; }
    seen.add(event.id); balance += event.amount;
    trace.push(`Delivery ${n}: credited 100 units; balance = ${balance}.`);
  }
  return { pass: balance === 100, actual: balance, expected: 100, unit: 'units credited', trace };
}

// ---- ADAPTER: replace this body to test your own application ----
// Currently it calls the bundled repaired reference, so the tests below check the reference.
function underTest(condition) {
  return payment(true, condition);
}

const invariant = "Exactly 100 units are credited for any positive number of deliveries of this one event.";
const conditions = [
  {"value":3,"label":"3 deliveries","originalBreaks":true},
  {"value":5,"label":"5 deliveries","originalBreaks":true},
  {"value":1,"label":"1 delivery (control)","originalBreaks":false}
];

// Invariant checks: these run against underTest(), i.e. your adapter once connected.
for (const condition of conditions) {
  test(`${invariant} [${condition.label}]`, () => {
    const result = underTest(condition.value);
    assert.equal(result.pass, true);
    assert.deepEqual(result.actual, result.expected);
  });
}

// Negative controls: these always call the bundled ORIGINAL reference, never your adapter.
// They prove the invariant can fail, and that the no-failure controls pass.
for (const condition of conditions) {
  test(`Reference original ${condition.originalBreaks ? 'violates' : 'satisfies'} the invariant [${condition.label}]`, () => {
    assert.equal(payment(false, condition.value).pass, !condition.originalBreaks);
  });
}
