// Generated by Break Your Assumptions v0.1.0 (MIT)
// Lab: The last ticket - assumption: Checking availability is enough to prevent overselling.
// Run: node --test ticket.test.cjs
//
// WHAT THIS FILE TESTS
// As downloaded, this file verifies the reference implementation bundled below.
// It does NOT test your application until you connect an adapter: replace the body
// of underTest() with a call into YOUR code that returns {pass, actual, expected}
// derived from observed application state. See docs/ADAPTING_TESTS.md.

const test = require('node:test');
const assert = require('node:assert/strict');

// ---- Reference simulation (teaching model, self-contained) ----
function ticket(fixed, buyers = 2) {
  if (!Number.isInteger(buyers) || buyers < 1 || buyers > 1000) throw new RangeError('buyers must be an integer from 1 to 1000');
  let stock = 1, sold = 0;
  const trace = [];
  trace.push(fixed ? 'Each reservation checks and decrements stock in one atomic step.'
    : `${buyers === 1 ? 'The buyer reads' : `All ${buyers} buyers read`} stock = 1 before any write happens.`);
  // Broken schedule: all buyers read before any buyer writes.
  const snapshots = Array(buyers).fill(stock);
  for (let n = 0; n < buyers; n++) {
    const available = fixed ? stock : snapshots[n];
    if (available > 0) {
      stock = available - 1; sold++;
      trace.push(`Buyer ${n + 1}: reservation accepted; stock = ${stock}.`);
    } else trace.push(`Buyer ${n + 1}: sold out.`);
  }
  trace.push(`Result: ${sold} ticket${sold === 1 ? '' : 's'} sold from a stock of 1.`);
  return { pass: sold === 1, actual: sold, expected: 1, unit: 'tickets sold', trace };
}

// ---- ADAPTER: replace this body to test your own application ----
// Currently it calls the bundled repaired reference, so the tests below check the reference.
function underTest(condition) {
  return ticket(true, condition);
}

const invariant = "One unit of stock allows exactly one successful reservation.";
const conditions = [
  {"value":2,"label":"2 buyers","originalBreaks":true},
  {"value":4,"label":"4 buyers","originalBreaks":true},
  {"value":1,"label":"1 buyer (control)","originalBreaks":false}
];

// Invariant checks: these run against underTest(), i.e. your adapter once connected.
for (const condition of conditions) {
  test(`${invariant} [${condition.label}]`, () => {
    const result = underTest(condition.value);
    assert.equal(result.pass, true);
    assert.deepEqual(result.actual, result.expected);
  });
}

// Negative controls: these always call the bundled ORIGINAL reference, never your adapter.
// They prove the invariant can fail, and that the no-failure controls pass.
for (const condition of conditions) {
  test(`Reference original ${condition.originalBreaks ? 'violates' : 'satisfies'} the invariant [${condition.label}]`, () => {
    assert.equal(ticket(false, condition.value).pass, !condition.originalBreaks);
  });
}
