// Generated by Break Your Assumptions v0.1.0 (MIT)
// Lab: The invisible difference - assumption: Text that looks the same compares equal.
// Run: node --test unicode.test.cjs
//
// WHAT THIS FILE TESTS
// As downloaded, this file verifies the reference implementation bundled below.
// It does NOT test your application until you connect an adapter: replace the body
// of underTest() with a call into YOUR code that returns {pass, actual, expected}
// derived from observed application state. See docs/ADAPTING_TESTS.md.

const test = require('node:test');
const assert = require('node:assert/strict');

// ---- Reference simulation (teaching model, self-contained) ----
function unicode(fixed, form = 'accent') {
  if (form !== 'accent' && form !== 'ring') throw new RangeError('form must be "accent" or "ring"');
  const pairs = { accent: ['caf\u00e9', 'cafe\u0301'], ring: ['\u00c5', 'A\u030a'] };
  const [stored, query] = pairs[form];
  const actual = fixed ? stored.normalize('NFC') === query.normalize('NFC') : stored === query;
  const points = s => [...s].map(c => 'U+' + c.codePointAt(0).toString(16).toUpperCase().padStart(4, '0')).join(' ');
  return { pass: actual, actual: actual ? 'Match' : 'No match', expected: 'Match', unit: 'search result',
    trace: [`Stored: ${stored} (${points(stored)}).`, `Query: ${query} (${points(query)}).`,
      fixed ? 'Normalize both strings to NFC before equality.' : 'Compare raw code-point sequences.'] };
}

// ---- ADAPTER: replace this body to test your own application ----
// Currently it calls the bundled repaired reference, so the tests below check the reference.
function underTest(condition) {
  return unicode(true, condition);
}

const invariant = "These canonically equivalent example strings match after NFC normalization.";
const conditions = [
  {"value":"accent","label":"café / combining accent","originalBreaks":true},
  {"value":"ring","label":"Å / combining ring","originalBreaks":true}
];

// Invariant checks: these run against underTest(), i.e. your adapter once connected.
for (const condition of conditions) {
  test(`${invariant} [${condition.label}]`, () => {
    const result = underTest(condition.value);
    assert.equal(result.pass, true);
    assert.deepEqual(result.actual, result.expected);
  });
}

// Negative controls: these always call the bundled ORIGINAL reference, never your adapter.
// They prove the invariant can fail, and that the no-failure controls pass.
for (const condition of conditions) {
  test(`Reference original ${condition.originalBreaks ? 'violates' : 'satisfies'} the invariant [${condition.label}]`, () => {
    assert.equal(unicode(false, condition.value).pass, !condition.originalBreaks);
  });
}
